apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  destination:
    namespace: infra-tools
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 13.8.4
    helm:
      valuesObject:
        auth:
          rootUser: minio
          rootPassword: minio123
        defaultBuckets: "mlflow-artifacts"
        service:
          type: ClusterIP
        persistence:
          enabled: false
        image:
          repository: docker.io/bitnami/minio
          tag: 2025.3.12-debian-12-r1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
