apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: infra-tools   # ArgoCD у тебе в infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/sergii-edu/mlops-ci-cd.git   # ← твій репозиторій
    targetRevision: lesson-8-9   # ← твоя гілка
    path: goit-argo/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
